name: NTAC
main: net.newtownia.NTAC.NTAC
version: '1.9-b2'
depend: [NTApi, ProtocolLib]
author: VincBreaker

commands:
  ntac:
    description: 'General NTAC-handling'
    usage: '/ntac'
    permission: ntac.command
  ntacreload:
    description: 'Laedt das Plugin neu.'
    usuage: '/ntacreload'
    permission: ntac.reload

permissions:
  ntac.bypass.killaura.npc:
    default: OP
  ntac.bypass.antiknockback:
    default: OP
  ntac.bypass.autoclicker:
    default: OP
  ntac.bypass.skinderp:
    default: OP
  ntac.bypass.headless:
      default: OP
  ntac.bypass.antiafk:
    default: OP
  ntac.bypass.sneak:
    default: OP
  ntac.bypass.noslowblock:
    default: OP
  ntac.bypass.fastladder:
    default: OP
  ntac.bypass.boatfly:
    default: OP
  ntac.bypass.inventory-move:
    default: OP
  ntac.command.notify:
    default: OP
  ntac.command.kick:
    default: OP
  ntac.command.reload:
    default: OP
  ntac.notify:
    default: OP