#GENERAL INFORMATION

#String formating:
#Colors:
#You can use the essentials color codes
#        http://ess.khhq.net/mc/

# Orig Chars --> Will be replaced with
#
# %n         --> A new line
# %nn        --> 5 new lines

#Unit: Tick:
#"Tick" is a minecraft-time-unit.
#20 Ticks equal one second
#Example = 3 Seconds = 3 * 20 = 60 Ticks

#ENABLED MODULES
Enabled:

  #Combat
  Killaura-NPC: true # Stable DEFAULT: true
  Aimbot: false # False positives, fixed soon :D
  Anti-Knockback: true # Recoded and awesome DEFAULT: true
  Auto-Clicker: true # Code stable, customize dat settings DEFAULT: true
  Criticals: true # Stable, by HorizonCode DEFAULT: true
  Auto-Armor: false # Stable, take a look at InvMove too! DEFAULT: true
  Combat-Reach: true # Stable, DEFAULT: true

  #Movement (all require movement base enabled)
  Speed: true # Stable, fixes Speeds bypassing NC+, BETA, please report any false positives DEFAULT: true
  Boat-Fly: true # Stable, fixes the most common 1.9 fly bypass using boats. :D DEFAULT: true
  NCP-Drag-Down: true # Drag players down if NoCheatPlus detects fly
  Jesus: true # Stable DEFAULT: true (by HorizonCode)
  Bad-Packets: true # Fixes blink / damage exploits / regen, all movement spammy hacks
  Sneak: true # Stable, patches a NC+ Bypass DEFAULT: true
  Fast-Ladder: true # Stable, NC+ is unable to fix it :(
  Inventory-Move: true # Blocks all moves when inventory is open / item-actions if inv is not open,
    # may fuck up archivements, may have false positives DEFAULT: true
  Anti-AFK: false # Beta, testing on newtownia.net + more subchecks'll be added soon! DEFAULT: true
  Freecam: true # Blocks freecam by abusing a bug in many freecams...

  # Player
  SkinDerp: true # Stable, even in AAC --> Hive! DEFAULT: true
  Headless: true # Stable :D
  Abilities: true # Cancel suspicious client abilities (e.g. vanilla-fly) (by HorizonCode)

  # Render
  #Tracers: true # Not implemented yet :/

  # Miscellanious
  Anti-Chorus-Fruit: true # Block teleportation caused by chorus fruit to prevent people to teleport trough walls

# ///////////////////////////////////////////////////////////////////
# General settings
# ///////////////////////////////////////////////////////////////////

Auto-Ban:

  # Should people be automaticly be banned?
  # The vl is equal to the points given by the /ntac addbanpoint <Player> <Amount> command,
  # so you can put you're own weights to certain checks :D
  # REMOVE THE HASHTAGS BEFORE THE LINES TO ENABLE AUTO-BANNING

  #Actions:
  #  3: "ntac ban %PLAYER% 15m"
  #  4: "ntac ban %PLAYER% 1h"
  #  5: "ntac ban %PLAYER% %VL%h"

  # REMOVE THIS LINE WHEN ENABLING AUTO-BANNING
  Actions:
    10000: 'cancel'

# Some options for the bases of NTAC
Bases:

  # The movement base is a part of the integrated framework which keeps
  # tracking the player movement and saves serveral position data
  # Can be disabled if you don't use any of the movement checks
  # If disabled the movement base, enabled movement checks will be buggy / not working
  Enable-Movement-Base: true

  # The combat base is required for every combat check (e.g. Killaura-NPC; AutoClicker)
  Enable-Combat-Base: true


# ///////////////////////////////////////////////////////////////////
# Combat hacks
# ///////////////////////////////////////////////////////////////////

# Killaura NPC-Check settings
Killaura-NPC:

  # Combat time
  # Time (in milliseconds (1000 ms equal 1 sec) the bot is visible after
  # hitting an entity
  # DEFAULT: 5000  (equals 5 seconds)
  Combat-Time: 5000

  # Should NTAC always create a fake identity, this fixes some incompatiblity issues
  # but allowes some bypasses
  Only-Random-Identity: false

  # Should the bot be of the same type as the attacked entity?
  # Used to patch mobaura which ignores players.
  # If false, the bot will always be a player
  # Only-Random-Identity need to be set to false to apply this value!
  Copy-Attacked-Type: true

  # How high should the bot be, anything under 2.7 may affect PvP, anything above 4.5 may be out of range
  Min-Height: 3.4
  Max-Height: 4
  Jump-Multiplier: 1.3

  # How far away should the bot be (on x and y axis)
  Min-Distance: 2
  Max-Distance: 4

  # Which angle should the bot have in relation the the player pitch
  Angle: 90

  # Set to something >= 100 to disable the bot going down, will unpatch some bypasses
  Down-Probability: 95

  # Slow weapon vl increasement
  # How much should the vl be increased when the player is using a slow weapon, e.g. an axe
  Slow-Weapon-Increment: 2

  #The commands run when a player is suspected for killaura
  #Each violation is equal to a hit
  Actions:
    2: "ntac respawn %PLAYER%"
    6:
      - "ntac addbanpoint %PLAYER% 1"
      - "ntac kick %PLAYER% %%Kick-Killaura%%"
      - "ntac notify %%Notify-Killaura-Kick%%"

Aimbot:

  # How many angles should the Aimbot-Check save?
  Data-Count: 5

  # How far are the angles allowed to fall apart to still
  # be assumed as hacking
  Angle-Threshold: 5

  # How much must the head move the be checked for aimbot,
  # important to fix false positives while the player is not
  # moving the head
  Min-Yaw: 5

  # How long should there be no new violations until they are resettet?
  Invalidate-Threshold: 60000

  # Actions, the VL is equal to the amount of suspicious hits
  Actions:
    2:
      - 'ntac addbanpoint %PLAYER% 1'
      - 'ntac kick %PLAYER% %%Kick-Aimbot%%'
      - 'ntac notify %%Notify-Aimbot-Kick%%'

# Auto-Clicker-Check, in development
Auto-Clicker:

  # The count of stored delays, set higher to reduce false positives, will use more cpu and ram
  Delay-Count: 10

  # How many milliseconds should be used as puffer to make the check usefull
  Timer-Puffer: 12

  # The time between two hits to ignore that delay to make autoclicker more precise
  Combat-Time: 5000

  # The vl is equal to the amount of detected attacs
  Actions:
    5:
      - 'ntac notify %%Notify-Autoclicker-Suspect%%'
      - 'ntac respawn %PLAYER%'
    10:
      - 'ntac addbanpoint %PLAYER% 1'
      - 'ntac kick %PLAYER% %%Kick-Autoclicker%%'
      - 'ntac notify %%Notify-Autoclicker-Kick%%'

  # The time until the VL get's invalidated (in ms)
  # NOTE: The VL only get's invalidated when there are no new VLs.
  Invalidate-Threshold: 60000

# Anti-Knockback / NoVelocity-Check
Anti-Knockback:

  # The adjustment is a delay (in ticks) to give player more time to move even if he should already have
  Adjustment: 3

  # Every velocity which is weaker than the given value on the y axis will be ignored
  Minimum-Y-Velocity: 0.05

  # The time until the VL get's invalidated (in ms)
  # NOTE: The VL only get's invalidated when there are no new VLs.
  Invalidate-Threshold: 60000

  # The VL equals the count of velocitys the players did not react to
  Actions:
    5:
      - 'ntac kick %PLAYER% %%Kick-AntiKnockback%%'
      - 'ntac notify %%Notify-AntiKnockback-Kick%%'

Criticals:

  # The time until the VL get's invalidated (in ms)
  # NOTE: The VL only get's invalidated when there are no new VLs.
  Invalidate-Threshold: 60000

  # Action data, VL equal to the count of suspicious attacks
  Actions:
    3: 'cancel'
    5:
      - "ntac respawn %PLAYER%"
      - "cancel"
    20:
      - 'ntac kick %PLAYER% %%Kick-Criticals%%'
      - 'ntac notify %%Notify-Criticals-Kick%%'

# AutoArmor works by adding a special diamond chestplate to the inventory of the player looks up if the player
# put it on in a certain time.
Auto-Armor:

  # How often (time between checks in seconds) should NTAC run the check
  Check-Frequency: 300

  # How long (in ticks) should the check pass on
  Check-Time: 20

  # How should the chestplace be named. Use this to leave a message to legit player NOT put the chestplate on
  # (SUPPORTS custom messages)
  Item-Name: '&4&lNICHT ANZIEHEN'

  # Commands run when the player is suspected for AutoArmor.
  Actions:
    8:
      - 'ntac kick %PLAYER% %%Kick-AutoArmor%%'
      - 'ntac notify %%Notify-AutoArmor-Kick%%'

# Deny hitting entities to far away from the player...
Combat-Reach:

  # How far away should the attacker be from the target to be counted as hacker?
  Max-Reach: 3.6

  # The time until the VL get's invalidated (in ms)
  # NOTE: The VL only get's invalidated when there are no new VLs.
  Invalidate-Threshold: 60000

  # The vl is equal to the amount of hits which are to far away from the target.
  Actions:
    3: 'cancel'
    8:
      - 'ntac kick %PLAYER% %%Kick-CombatReach%%'
      - 'ntac notify %%Notify-CombatReach-Kick%%'

# ///////////////////////////////////////////////////////////////////
# Movement hacks
# ///////////////////////////////////////////////////////////////////

Speed:

  # Block people going faster than sonic, values skidded from AAC
  # https://gist.github.com/konsolas/67108a5d48a90fa6964c

  # Basic speeds
  Sprinting: 0.83
  Sneaking: 0.215
  Cobweb: 0.2
  Ice: 1.7
  Stairs: 1.5

  Jump-Multiplier: 1.8
  Velocity-Multiplier: 2

  # Potion-Multipliers
  Speed-Potion: 1.45
  Slow-Potion: 0.8

  # The vl is increased by (expectedSpeed - actualSpeed) * thisValue
  VL-Multiplier: 3
  # How fast should the VL decrease
  VL-Decrease: 2
  # How long (after an detection) should the vl NOT decrease (in milliseconds)
  No-Decrease-Time: 300
  # To prevent setback-exploits
  Max-VL: 10

  # VL equals the amount of suspicious moves
  Actions:
    8: 'cancel' # The VL can increase up to 4 in combat by knockback and up to 1 by jumping...

Boat-Fly:

  # The time until the VL get's invalidated (in ms)
  # NOTE: The VL only get's invalidated when there are no new VLs.
  Invalidate-Threshold: 250

  # Should all movements upwards be cancelled? Suggested if the first VL with 'cancel' is above 1
  # to prevent some bypasses and eventually exploits
  Cancel-All-Up-Movements: true

  # How long should boats be off ground untill they get checked? (Moves)
  Min-Offground-Moves: 3

  # How fast do someone have to fall to get ignored by the check
  # This reenables the ability to glide legit with a boat. If you higher the value,
  # you'll have to higher the Friction-Min-Time to prevent false positives.
  # Set to Ignore-Threshold to 0 and the actions to 0: 'cancel' to completly disable falling
  # with boats (no more MLG-Legit-Boatgliding)
  Min-Down-Speed: 0.12

  # Actions, the VL is equal to the count of suspicious movements
  Actions:
    2: 'cancel'
    10: 'ntac kick %PLAYER% %%Kick-Movement%%'

NCP-Drag-Down:

  # The time until the VL get's invalidated (in ms)
  # This is required for the position on the x and z axis to be
  # sure that no one flyes very fast while abusing going down slowly
  # NOTE: The VL only get's invalidated when there are no new VLs.
  Invalidate-Threshold: 250

Jesus:

  # Should jesus care about the jumping in water? This will fix several bypasses
  Jump-Jesus: true

  # Actions performed when player is suspected for jesus, VL equals to the count of suspicious moves.
  Actions:
    2: 'cancel' # First cancel should be at lease 2 to fix a "Wrong movement" false positive
    5:
      - 'ntac kick %PLAYER% %%Kick-Movement%%'
      - 'ntac notify %%Notify-Jesus-Kick%%'

Bad-Packets:

  # VL is equal to the packets send withing 3 ticks
  Actions:
    50:
     - 'cancel'
     - 'ntac notify %%Notify-Bad-Packets-Suspect%%'
     - "ntac respawn %PLAYER%"

# Sneak properties
# NOTE: This check isn't ment to be a completly check for Sneak. It is a patch for NC+ fixes a bypass (for NC+)
Sneak:

  # The time between to sneak actions to get detected as legit.
  Sneak-Threshold: 40

  # Actions, the vl equals the count of detected packets
  Actions:
    3: 'cancel'
    20:
      - 'ntac notify %%Notify-Sneak-Suspect%%'
      - 'cancel'
    100:
      - 'ntac kick %PLAYER% %%Kick-Movement%%'
      - 'ntac notify %%Notify-Sneak-Kick%%'

  # The time until the VL get's invalidated (in ms)
  # NOTE: The VL only get's invalidated when there are no new VLs.
  Invalidate-Threshold: 1000

  # The frequencie (in ticks) for the invalidate-cycle
  Invalidate-Freq: 5

Fast-Ladder:

  # The normal climbing speed
  Climbing-Speed: 0.13

  # The speed allowed when you start to climb a ladder
  Start-Speed: 1.5

  # The time until the VL get's invalidated (in ms)
  # NOTE: The VL only get's invalidated when there are no new VLs.
  Invalidate-Threshold: 250

  # The actions, the vl equals the count of suspicious movements
  Actions:
    3: 'cancel'
    25:
      - 'ntac kick %PLAYER% %%Kick-Movement%%'
      - 'ntac notify %%Notify-FastLadder-Kick%%'

Inventory-Move:

  # Should all item-actions be blocked when the invenotry is closed? This fixes
  # AutoArmor. Note that actions with items in the hotbar wont be blocked since
  # you are able right click them to put armor on...
  Cancel-Item-Actions: true

  # How long after opening the inventory / getting damage should players be ignored
  Grace-Time: 1000

  # The time until the VL get's invalidated (in ms)
  # NOTE: The VL only get's invalidated when there are no new VLs.
  Invalidate-Threshold: 250

  # Actions performed when player moves while the inv is opened, VL equals the count of moves
  Actions:
    2: 'cancel'
    10:
      - 'ntac kick %PLAYER% %%Kick-Movement%%'
      - 'ntac notify %%Notify-InvMove-Kick%%'

# Anti-AFK
Anti-AFK:
  # Time (in seconds) of a player being afk until he get's kicked. DEFAULT: 300
  Kick-Threshold: 180

  # Frequency for the check weather a player should be kicked. DEFAULT: 100
  Kick-Check-Frequency: 100

  # The message shown when a player is kicked cause AFK. DEFAULT: AFK
  Kick-Message: '%%Kick-AFK%%'

  # Subcheck-Properties

  # Move-In-Range-Check
  # This check checks weather the player has moved a several distance
  Move-In-Range:

    # Should this subcheck be enabled DEFAULT: true
    Enabled: false

    # This is the distance a player have to walk until the movement is
    # recognized as not-afk (bot) movement by the MoveInRange-Check
    # This is limit to 2 for testings purposes and to limit false-positives at the
    # beginning. DEFAULT: 2
    Range-Threshold: 2

  # Push-Device-Check
  # This check checks weather the player is in water, lava or riding to kill
  # AFK-Maschines, experimental (and work in progress)
  Push-Device-Check:

    # Should this subcheck be enabled DEFAULT: true
    Enabled: true

    # Should movements in water be marked as AFK. DEFAULT: true
    Mark-In-Water: true

    # Should movements in lava be marked as AFK. DEFAULT: true
    Mark-In-Lava: true

    # Should movements while the player is riding or using a minecart be marked as AFK. DEFAULT: true
    Mark-In-Vehicle: true

    # The delay (ms) until a player is unmarked, required to ignore steps in afk-maschines (also fixes infinite jump-maschines) DEFAULT: 3000
    Unmark-Delay: 3000



# ///////////////////////////////////////////////////////////////////
# Player hacks
# ///////////////////////////////////////////////////////////////////

# Skinderp-Properties:
SkinDerp:

  # Time between skin-changes to make a change legit (Milliseconds) DEFAULT: 100
  Time-Threshold: 100

  # Count of unlegit changes till the player get kicked DEFAULT: 10
  Count-Threshold: 50

  # Kick-message DEFAULT: Skinderp
  Kick-Message: Skinderp

  # The commands run when a player is suspected for killaura
  # Each violation is equal to a hit
  Actions:
    10:
      - 'ntac kick %PLAYER% %%Kick-Derp%%'
      - 'ntac notify %%Notify-Derp-Kick%%'

# Headless
Headless:

  # The commands run when someone get suspected for headless, the vl is equal to the count of suspicious movements
  Actions:
    1:
      - 'ntac kick %PLAYER% %%Kick-Derp%%'
      - 'ntac notify %%Notify-Derp-Kick%%'

Abilities:

  # This abuses a bug in almost every vanilla-fly (creative-fly)
  Vanilla-Fly: true

  Actions:
    10:
      - 'ntac kick %PLAYER% %%Kick-Actions%%'
      - 'ntac notify %%Notify-Abilities-Kick%%'